import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components";

const proximaNova = localFont({
  src: [
    { path: "../../public/ProximaNova-Regular.woff2", weight: "400" },
    { path: "../../public/ProximaNova-Semibold.woff2", weight: "600" },
    { path: "../../public/ProximaNova-Bold.woff2", weight: "700" },
  ],
  variable: "--font-proxima-nova",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${proximaNova.variable} font-proxima-nova`}>
        <Header />
        <main className="mx-auto pb-[56px] pt-[54px] max-w-[1920px]">
          {children}
        </main>
      </body>
    </html>
  );
}
